# Generated by Django 6.1 on 2026-08-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('in_use', 'In Use'), ('repair', 'Repair')], max_length=20)),
                ('external_id', models.IntegerField(blank=True, help_text="id from the source data.json this row was imported from. Not a database key — duplicates are expected and don't collide with anything.", null=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Any source fields not mapped to a column above (notes, assignedTo, history, ...).')),
                ('needs_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
