# Generated by Django 6.1 on 2026-08-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_hardware_rented_at_hardware_rented_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='embedding',
            field=models.JSONField(blank=True, default=None, editable=False, null=True),
        ),
    ]
